### ISSUE TITLE
How to Deploy via cPanel

### ISSUE THREAD

**Issue by HarrisonMayotte** [Jon-Peppinck/linkedin-clone#1]
Hi there,
When trying to deploy the application using the "Setup Node.js Application" tool in cPanel, I tried using the contents of the folder in "dist" but that doesn't seem to work because there's no package.json.

Is there a deployment instruction sheet somewhere?

Thanks.

**Comment by Jon-Peppinck** [comment]
Planning on covering some DevOps topics such as deployments via AWS for NestJS backends on my YT channel in the coming months.
